version: '3.7'

services:
  apinode:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - PORT=${PORT:-3000}
      - ENVIRONMENT=${ENVIRONMENT:-dev}
      - POSTGRES_HOST=${DB_HOST:-db}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-nodeProject}
      - POSTGRES_USER=${DB_USER:-admin}
      - POSTGRES_DB=${DB_NAME:-cowork}
      - POSTGRES_PORT=${DB_PORT:-5432}
    volumes:
      - .:/usr/src/app
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    command: /bin/sh -c 'chmod +x ./start.sh && ./start.sh'
  db:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:-nodeProject}
      - POSTGRES_USER=${DB_USER:-admin}
      - POSTGRES_DB=${DB_NAME:-cowork}
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
volumes:
  dbdata:
